SMTP:
    smtp_host: smtp.mxhichina.com
    smtp_port: 465
    smtp_user: xxxx@xxxx.cn
    smtp_alias: Alert Inconformity
    smtp_password: xxxx
    mail_to_list: ['user1@i-counting.cn','user2@i-counting.cn']
