#yaml文件本身就是一个序列化后的字典，可通过yaml.load反序列化成字典
SMTP:
    smtp_host: smtp.exmail.qq.com
    smtp_port: 465
    smtp_user:  Alert@agrant.cn
    smtp_alias: Alert1111
    smtp_password: 
    mail_to_list: ['14339989@qq.com','jianbo.yu@agrant.cn']
